# Welcome to Jekyll!

title:                  "Physics for everyone!"
email:                  "johanna.jochum@frm2.tum.de"
description:            "You donâ€™t need to be a genius to learn about physics! Sometimes you just need someone to help you navigate through all the jargon."

baseurl:                "/SciComm_Blog"
url:                    "/SciComm_Blog"

# Build settings
markdown:               kramdown
theme:                  minima
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate:               6
permalink:              pretty
mailchimp_link:         "//themeix.us16.list-manage.com/subscribe?u=4b7aa1c5c5ac54be844d58bcb&id=0e85c09412"

# social links

twitter_username:       "jkj_2309"
linkedin_username:      "johanna-k-jochum-b2910251"
github_username:        "jjochum87"
